name: compile

on: [ push, pull_request ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with: { version: 0.15.1 }

      - uses: actions/checkout@v5

      - run: zig env
      - run: zig build
      - run: zig build test
      - run: zig build cross
