on:
  release:
    types: [created, released]

jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with: { version: 0.15.1 }

      - uses: actions/checkout@v5

      - run: zig env
      - run: zig build test
      - run: zig build cross -Doptimize=ReleaseSmall

      - name: Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zig-out/cross/*/findup-*.tgz'
